steps:
  # ── Step 1: Build Docker image ───────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    id: build
    args:
      - build
      - -t
      - "us-central1-docker.pkg.dev/hackathon-java/${_REPO_NAME}/${_SERVICE_NAME}:$BUILD_ID"
      - -t
      - "us-central1-docker.pkg.dev/hackathon-java/${_REPO_NAME}/${_SERVICE_NAME}:latest"
      - .

  # ── Step 2: Push image to Artifact Registry ──────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - push
      - --all-tags
      - "us-central1-docker.pkg.dev/hackathon-java/${_REPO_NAME}/${_SERVICE_NAME}"

  # ── Step 3: Deploy to Cloud Run ──────────────────────────────────────
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "${_SERVICE_NAME}"
      - --image=us-central1-docker.pkg.dev/hackathon-java/${_REPO_NAME}/${_SERVICE_NAME}:$BUILD_ID
      - --region=${_REGION}
      - --platform=managed
      - --port=8350
      - --memory=2Gi
      - --cpu=2
      - --min-instances=1
      - --max-instances=5
      - --timeout=300
      - --allow-unauthenticated
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,MCP_SERVER_HOST=MCP_SERVER_HOST:latest,MCP_SERVER_PORT=MCP_SERVER_PORT:latest

# ── Substitution defaults ─────────────────────────────────────────────
substitutions:
  _REGION: us-central1
  _REPO_NAME: cloud-run-apps
  _SERVICE_NAME: eagle-eye-banking-app-agentic-backend

# ── Image tracking ────────────────────────────────────────────────────
images:
  - "us-central1-docker.pkg.dev/hackathon-java/${_REPO_NAME}/${_SERVICE_NAME}:$BUILD_ID"
  - "us-central1-docker.pkg.dev/hackathon-java/${_REPO_NAME}/${_SERVICE_NAME}:latest"

# ── Build options ─────────────────────────────────────────────────────
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
